### PR TITLE
Header enhancements

### PR DESCRIPTION
**Pull request by aparajitaghimire**
Added header enhancements to make it smaller, more reusable, and to change colour of tab when it's selected

### CODE REVIEW

**Review by nehageorge — APPROVED** [review]
Beautiful code, really! And great assist today at the Waterloo Worriers game... LGTM!!

**Comment by jackpalaia** [comment]
Rewrite this in C please!

**Comment by ZhengmaoOuyang** [comment]
> Rewrite this in C please!

WHAT ARE YOU DOING HERE!!!!!

**Comment by aparajitaghimire** [comment]
Thanks team members and lurkers 🙏🏽

**Pull request merged**
