### PR TITLE
Aparajita/75: frontend of upload previously approved equivalency popup

### PR DESCRIPTION
**Pull request by aparajitaghimire**
Screenshot 2023-07-26 at 1 49 48 PM

Screenshot 2023-07-26 at 1 52 14 PM

Screenshot 2023-07-26 at 2 55 52 PM

### CODE REVIEW

**Review by ZhengmaoOuyang — APPROVED** [review]
ur the best... around!!!! nothings gonna ever bring y down

**Review by AndreaMiranda99 — COMMENTED** [review]
Does this only appear if a user is logged in?

**Comment by ZhengmaoOuyang** [comment]
please disregard my approval bc andrea has a comment

**Review by AndreaMiranda99 — APPROVED** [review]
TY ! Now we're more secure 😀

**Pull request merged**
